### ISSUE TITLE
关于浙大版《C语言程序设计（第3版）》5-7题

### ISSUE THREAD

**Issue by DIsraeliG** [nialin/C-Language-Programming#1]
您好，在PTA上运行了您的5-7题的代码，发现在测试点1”精度高，不可直接计算阶乘“无法AC，我的代码也遇到了相同的问题，想请教您一下，如何解决该问题。

**Comment by nialin** [comment]
您好，
  刚刚我重新提交我的代码测试了一下，没有发现你说的问题。










在 2020-04-10 13:08:03，"DIsraeliG" <notifications@github.com> 写道：

您好，在PTA上运行了您的5-7题的代码，发现在测试点1”精度高，不可直接计算阶乘“无法AC，我的代码也遇到了相同的问题，想请教您一下，如何解决该问题。

**Comment by DIsraeliG** [comment]
谢谢您的回复，我又试了一遍，通过了

**Comment by nialin** [comment]
不客气










在 2020-05-08 19:27:17，"DIsraeliG" <notifications@github.com> 写道：

谢谢您的回复
